name: netflix
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  bloc: ^8.1.3
  http: ^1.1.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_native_splash: ^2.3.7
  go_router: ^13.2.0
  shared_preferences: ^2.2.3
  youtube_player_flutter: ^9.0.0
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  fluttertoast: ^8.0.9
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6
  google_generative_ai: ^0.4.1
  flutter_markdown: ^0.6.19
  hydrated_bloc: ^8.0.0
  path_provider: ^2.1.3
  flutter_colorpicker: ^1.1.0
  lottie: ^2.7.0
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/playstore.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/playstore.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
